### ISSUE TITLE
AdaptyPaywallControllerDelegate not implementable?

### ISSUE THREAD

**Issue by frogg** [adaptyteam/AdaptyUI-iOS#1]
I am trying to make my `AppDelegate` conform to `AdaptyPaywallControllerDelegate` so I can make use of the `AdaptyUI.paywallController`.

When I try to make the AppDelegate conform to the protocol, this happens:

<img width="856" alt="Screenshot 2023-07-22 at 16 45 43" src="https://github.com/adaptyteam/AdaptyUI-iOS/assets/5204169/ed239f3a-c2f3-40dd-95f5-bfa3c0be0c5d">

<img width="857" alt="Screenshot 2023-07-22 at 16 45 54" src="https://github.com/adaptyteam/AdaptyUI-iOS/assets/5204169/9d464dd5-2ef3-4c42-a01e-e2d2108d7d13">

Any idea what I’m doing wrong here with the implementation?

**Comment by x401om** [comment]
Hey, @frogg. Just remove all the `AdaptyUI.` and `Adapty.` prefixes before parameters declarations and errors will gone. Take a look at our Example app of you have any questions regarding the integration.
