### ISSUE TITLE
Compiler errors: Incompatible version in CocoaPods

### ISSUE THREAD

**Issue by faris-mobile89** [adaptyteam/AdaptyUI-iOS#4]
Please update Adapty version in the podspec to get the latest version.

> AdaptyUI.podspec -> _s.dependency 'Adapty', '2.9.5'_  to be  **s.dependency 'Adapty', '2.9.6'**

Commit

> update version to 2.9.6
> --
> [update version to 2.9.6](https://github.com/adaptyteam/AdaptySDK-iOS/commit/a85d0ea54a8f801bc1887fc163b4aa4835c7b551)

**Comment by x401om** [comment]
Hi, @faris-mobile89! That is definitely my mistake, thank you!

upd: PR is merged, pod is [updated](https://cocoapods.org/pods/AdaptyUI)
