### ISSUE TITLE
 'delegate' parameter is incorrectly marked as optional in docs

### ISSUE THREAD

**Issue by TweedBeetle** [adaptyteam/AdaptyUI-iOS#5]
The [documentation for the AdaptyUI.paywallController method](https://docs.adapty.io/docs/paywall-builder-presenting-ios) states that the 'delegate' parameter is optional. However, in practice this parameter seems to be required.

When calling paywallController without providing a delegate object, I get a "Missing argument for parameter 'delegate' in call" error:

<img width="968" alt="image" src="https://github.com/adaptyteam/AdaptyUI-iOS/assets/12238004/4ed202fa-8f2c-466b-9c3a-ced12a31066f">

It's unclear what to provide for the 'delegate' when you don't actually need to listen for paywall events. The current options are to either provide a dummy delegate object, or to always implement a delegate even if it's not needed.

Let me know if you need any other details or have questions!

**Comment by x401om** [comment]
Hi, @TweedBeetle! Thank you for noticing this. The delegate is indeed a required parameter at the moment, as not all the methods have default implementations. I have updated the documentation, and we will consider making it optional in the future releases.
