### ISSUE TITLE
Clarify presenting visual paywall in SwiftUI

### ISSUE THREAD

**Issue by TweedBeetle** [adaptyteam/AdaptyUI-iOS#6]
The [current documentation for presenting a visual paywall on iOS](https://docs.adapty.io/docs/paywall-builder-presenting-ios) is unclear when using SwiftUI. It shows an example of calling `present(visualPaywall, animated: true)` to display the configured `AdaptyPaywallController`. 

However, in SwiftUI, there is no `present` function available on `View` types. SwiftUI uses a declarative approach with `sheet` or `fullScreenCover` modifiers to present views modally.

Could you perhaps provide an example of how to properly present the `AdaptyPaywallController` in a SwiftUI view? 

For example, would it be something like this?

```swift
struct ContentView: View {
    @State private var isPaywallPresented = false
    
    var body: some View {
        VStack {
            Button("Show Paywall") {
                isPaywallPresented = true
            }
        }
        .sheet(isPresented: $isPaywallPresented) {
            PaywallView()
        }
    }
}

struct PaywallView: View {
    var body: some View {
        let visualPaywall = AdaptyUI.paywallController(
            for: <paywall object>,
            products: <paywall products array>,
            viewConfiguration: <LocalizedViewConfiguration>,
            delegate: <AdaptyPaywallControllerDelegate>,
            tagResolver: <dictionary of custom tags and their values>
        )
        
        // How to present the visualPaywall here?
    }
}
```

It would be helpful to have a clear example of integrating the `AdaptyPaywallController` into a SwiftUI view hierarchy.

Additionally, if there are any SwiftUI-specific considerations or best practices when using Adapty's visual paywall feature, it would be amazing if these could be included in the documentation!

**Comment by x401om** [comment]
Hi, @TweedBeetle! We have updated our documentation for SwiftUI, you can find it [here](https://docs.adapty.io/docs/ios-present-paywalls#present-paywalls-in-swiftui) and [there](https://docs.adapty.io/docs/ios-handling-events#handling-events-in-swiftui).

**Comment by TweedBeetle** [comment]
Thank you, I appreciate it!
